name: twake
description: Mobile version of Twake application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 4.0.1 # serialization/deserialization auto code generation
  dio: ^4.0.0
  intl: ^0.17.0
  path_provider: ^2.0.1
  # sticky_grouped_list: ^2.0.0-nullsafety.1
  # sticky_grouped_list:
  #   # path: /home/bobur/work/sticky_grouped_list
  #   git: https://github.com/bobs4462/sticky_grouped_list.git
  grouped_list: 
    git: https://github.com/bobs4462/grouped_list.git
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  webview_flutter: ^2.0.8
  logger: ^1.0.0
  clipboard: ^0.1.3
  url_launcher: ^6.0.3
  package_info: ^2.0.0
  lottie: ^1.0.1
  sqflite: ^2.0.0+3
  tuple: 2.0.0
  flutter_segment: ^3.1.0
  sentry_flutter: ^5.1.0
  firebase_core: ^1.0.2
  firebase_messaging: ^10.0.0
  equatable: ^2.0.2
  flutter_bloc: ^7.0.1
  connectivity: ^3.0.4
  sliding_up_panel: ^2.0.0+1
  socket_io_client: ^1.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.1
  cached_network_image: ^3.0.0
  bubble: ^1.2.1
  emoji_picker_flutter: ^1.0.6
  flutter_appauth: ^2.0.0-dev.1


  flutter_local_notifications: ^6.0.0
  photo_view: ^0.11.1
  flutter_downloader: ^1.6.0
  permission_handler: ^8.1.1
  file_picker: ^3.0.2+2
  image: ^3.0.2
  get: ^4.1.4
  pull_to_refresh: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_launcher_icons: ^0.9.0
  test: ^1.15.8
  bloc_test: ^8.0.2 

flutter_icons:
  android: true
  ios: true
  image_path: 'dev_assets/logo.png'
  adaptive_icon_background: '#837DFF'
  adaptive_icon_foreground: 'dev_assets/logo_adaptive.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # animations
    - assets/animations/splash.json
    
    # images
    - assets/images/logo-white.png
    - assets/images/1024x1024.png
    - assets/images/oldtwakelogo.jpg
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # localization
    # - assets/translations/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PT
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PTSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PTSans-BoldItalic.ttf
          style: italic
          weight: 700
    - family: PTMono
      fonts:
        - asset: assets/fonts/PTMono-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          style: normal
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 900
          style: italic


    - family: Twake-Fontastic
      fonts:
        - asset: assets/fonts/twake-fontastic.ttf
