on:
  pull_request:
    # Only run the build when there's a pull request to main branch
    branches:
      - main
    paths-ignore:
      - "lib/l10n/**"
      - ".github/**"

name: Build app for testing and QA

jobs:
  analyze-and-test:
    name: Analyze and test the code
    uses: ./.github/workflows/analyze-and-test.yaml

  build-ipa:
    name: Build IPA
    needs:
      - analyze-and-test
    runs-on: macos-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # We use the pubspec as the cache key to detect dependencies changes
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.x"
          channel: "stable"
          cache: true
          cache-key: deps-${{ hashFiles('pubspec.lock') }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      # Taken from https://github.com/flutter/gallery/blob/main/.github/workflows/release_deploy_play_store.yml
      - name: Setup Google services
        run: |
          echo "$GOOGLE_SERVICES_PLIST" > Runner/GoogleService-Info.plist
        env:
          GOOGLE_SERVICES_PLIST: ${{ secrets.GOOGLE_SERVICES_PLIST }}
        working-directory: ios

      - name: Setup environment variables
        run: |
          echo "CAPTCHA_TOKEN=${{ secrets.CAPTCHA_TOKEN }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .firebase.env
          echo "APP_ID=${{ secrets.APP_ID }}" >> .firebase.env
          echo "MESSAGE_SENDER_ID=${{ secrets.MESSAGE_SENDER_ID }}" >> .firebase.env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .firebase.env

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.CERTIFICATE_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE_BASE64 }}
          SHAREEXT_PROVISION_PROFILE_BASE64: ${{ secrets.SHAREEXT_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          EXPORT_OPTIONS: ${{ secrets.EXPORT_OPTIONS }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          SHAREEXT_PP_PATH=$RUNNER_TEMP/shareext_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          echo -n "$SHAREEXT_PROVISION_PROFILE_BASE64" | base64 --decode --output $SHAREEXT_PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $SHAREEXT_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

          # create export options
          echo -n "$EXPORT_OPTIONS" > ExportOptions.plist

      - name: Build the IPAs
        run: |
          flutter build ipa -v --export-options-plist=ExportOptions.plist --debug

      - name: Upload IPAs
        uses: actions/upload-artifact@v3
        with:
          name: twake-ipa-pr-${{ github.event.number }}
          path: "build/ios/ipa/Twake.ipa"
          if-no-files-found: error

  build-apk:
    name: Build APK
    needs:
      - analyze-and-test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # We use the pubspec as the cache key to detect dependencies changes
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.x"
          channel: "stable"
          cache: true
          cache-key: deps-${{ hashFiles('pubspec.lock') }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "11"

      # Taken from https://github.com/flutter/gallery/blob/main/.github/workflows/release_deploy_play_store.yml
      - name: Setup keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY_BASE64" | base64 --decode > app/android.jks
          echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
          echo "$PLAY_STORE_KEY_INFO_BASE64" | base64 --decode > key.properties
        env:
          PLAY_STORE_UPLOAD_KEY_BASE64: ${{ secrets.PLAY_STORE_UPLOAD_KEY_BASE64 }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          PLAY_STORE_KEY_INFO_BASE64: ${{ secrets.PLAY_STORE_KEY_INFO_BASE64 }}
        working-directory: android

      - name: Setup environment variables
        run: |
          echo "CAPTCHA_TOKEN=${{ secrets.CAPTCHA_TOKEN }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .firebase.env
          echo "APP_ID=${{ secrets.APP_ID }}" >> .firebase.env
          echo "MESSAGE_SENDER_ID=${{ secrets.MESSAGE_SENDER_ID }}" >> .firebase.env
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .firebase.env

      - name: Build the APKs
        run: |
          flutter build apk -v --debug
          flutter build apk -v --release

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: "twake-apk-pr-${{ github.event.number }}"
          path: |
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

  comment-on-pr:
    name: Comment on PR
    needs:
      - build-ipa
      - build-apk
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Post a comment on PR, linking to the artifact URL of this run
      - name: Find comment on PR
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: "github-actions[bot]"

      - name: Create/update artifact URL comment on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            Download the artifacts :package: for this PR:
            - https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          edit-mode: replace
